name: Keep Backend Alive

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl backend
        run: curl -m 10 https://link-vault-3tke.onrender.com/health || true
